import Head from 'next/head'
import { Grid, Stack, Typography, Button } from '@mui/material'
import AppsIcon from '@mui/icons-material/Apps';
export default function Home() {
  return (
    <>
      <Head>
        <title>Pirate dev components</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Stack sx={{ width: '100%', py: 3 }} direction='row' justifyContent='center'><Typography variant="h2" color="initial" >Mis componentes personales</Typography></Stack>
        <Grid
          container
          spacing={1}
          direction="row"
          justifyContent="center"
          alignItems="center"
          alignContent="center"
          wrap="wrap"
        >
          <Stack sx={{ backgroundColor: 'red' }}>
            <Button variant="contained" color="primary" endIcon={<AppsIcon />}>
              Componentes
            </Button>
          </Stack>
        </Grid>
      </main>
    </>
  )
}
